algoritmo "ProcedimentoSomaAB"
var

N1, N2 : Inteiro

Procedimento Somador(A, B : Inteiro)
Inicio

Escreva ("A soma é ", A + B, "!")

FimProcedimento

inicio

Escreva ("Valor 1: ")
Leia (N1)
Escreva ("Valor 2: ")
Leia (N2)

Somador (N1, N2)


fimalgoritmo

//90) Desenvolva um algoritmo que leia dois valores pelo teclado e passe esses
//valores para um procedimento Somador() que vai calcular e mostrar a soma entre
//eles
